currencies:
  fromcurrencylist: "BTC,ETH,LTC,BCH"
  tocurrencylist: "USD"
http:
  address: ":8080" # The HTTP address to bind to
  readtimeout: 5 # in seconds
  writetimeout: 10 # in seconds
log:
  level: "INFO"
  logfile: ""
  maxsizemb: 500
  maxbackups: 7
  maxagedays: 10
  writestdout: true
  json: false
dbconn:
  user: "postgres"
  password: "sSyP2018"
  port: 5432
  host: "cryptobookdbinstance.c4fshiqizfeu.us-east-2.rds.amazonaws.com"
  dbname: "cryptopricesmulti"
environment: "local"
refreshinterval: 60
statsdhost: ""