currencies:
  currencylist: "BTC,ETH,LTC,BCH"
http:
  address: ":8080" # The HTTP address to bind to
  readtimeout: 5 # in seconds
  writetimeout: 10 # in seconds
log:
  level: "INFO"
  logfile: ""
  maxsizemb: 500
  maxbackups: 7
  maxagedays: 10
  writestdout: true
  json: false
environment: "local"
refreshinterval: 60
statsdhost: ""